theme: jekyll-theme-minimal
markdown: kramdown
name: Anton Zakharenkov
position: Data Scientist
github_url: https://github.com/zachanton
kaggle_url: https://www.kaggle.com/zachanton
linkedin_url: https://www.linkedin.com/in/anton-zakharenkov/
email_url: mailto:anton.zaharenkov@phystech.edu
resume_url: /assets/files/AntonZakharenkov_Resume.pdf
company_name: Conundrum
company_url: https://conundrum.ai
place_name: Warsaw, Poland
title: Anton Zakharenkov
description: Blog
url: https://zachanton.github.io/
logo: /assets/img/headshot.jpg
social:
  links:
    - https://www.linkedin.com/in/anton-zakharenkov/
    - https://github.com/zachanton
    - https://www.kaggle.com/zachanton
plugins:
  - jekyll-seo-tag
highlighter: rouge
header-includes:
  - \usepackage[ruled,vlined,linesnumbered]{algorithm2e}
  - \userpackage{amsmath}